#!/usr/bin/env tclsh
#

::tcl::tm::path add $::env(HOME)/lib/tcl8/site-tcl
package require jbr::msg

if { [catch {
	set server 	[lindex $argv 0]
	set variable 	[lindex $argv 1]
	set value 	[lrange $argv 2 end]

	msg_client $server
	puts [msg_set $server $variable $value]
	exit 0
} error] } {
	puts $error
	exit 1
}

